### PR TITLE
feat: Allow for % sizes in node size event

### PR DESCRIPTION
**Pull request by andrewreedy**
Currently the general size event only accepts true and absolute sizes. It would be helpful if it also would accept proportional sizes. This implementation uses strings with `%` on the end to denote proportional sizes. Now a node can be sized like so `size: ['100%', 300`].

### CODE REVIEW

**Comment by matthewtoast** [comment]
@andrewreedy Can you make your fork public? We wanted to review this before merging to look for potential GC issues. With a function like `size`, which is likely to be called frequently for animation, we _may_ need to write it in such a way as to avoid instantiating ephemeral arrays/objects which can lead to GC pauses and frame drops.

But in general I think this feature would be a great idea for the size API.

I am not an expert on GC so I'll cc @michaelobriena who can comment when he can take a look.

**Comment by andrewreedy** [comment]
@matthewtoast @michaelobriena That makes sense. I made the repo public.  Let me know what you think.  I'm not an expert on GC either :)

**Comment by michaelobriena** [comment]
I like the idea of generalizing size but have some issues with this.  I am not a fan that you pass a number for pixels and a String with a percent symbol for proportional.  This also does not account for differential (the loneliest size mode).  I would say that the size event should use the sizeMode values on to call the correct version and then it is only numbers passed in.

As for garbage, the axes lookup array can just be kept in closure at the file, doesn't need to be created every function call.  Everything else is pretty unavoidable.  Is the size passed into the function a copy of something or is it held onto forever?

**Comment by matthewtoast** [comment]
Going to close this since I think it requires a longer discussion.

**Pull request closed without merging**
